$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
ignorePaths:
  - node_modules
words:
  - astro
  - commitlint
  - ianvs
  - lockb
  - orbitkit
  - packagejson
  - tailwindcss
  - turborepo
